import Footer from './components/footer'
import Header from './components/header'
import UserSign from './components/userSign'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bugasoft Tour',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
 
  return (
    <html className=''  >
      
      <body className='w-screen h-screen'>
      
        <Header></Header>
        {children}
      <UserSign/>
      <Footer></Footer>
      </body>
    </html>
  )
}
